### ISSUE TITLE
Unsupported image type

### ISSUE THREAD

**Issue by Frotty** [inwc3/wc3libs#27]
Another minimap, this won't load at all.
```
javax.imageio.IIOException: Unsupported Image Type
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readInternal(JPEGImageReader.java:1068)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:1039)
	at javax.imageio.ImageIO.read(ImageIO.java:1448)
	at javax.imageio.ImageIO.read(ImageIO.java:1352)
	at net.moonlightflower.wc3libs.misc.image.JPG.read(JPG.java:15)
	at net.moonlightflower.wc3libs.misc.image.JPG.<init>(JPG.java:39)
	at net.moonlightflower.wc3libs.misc.image.BLP.read(BLP.java:194)
	at net.moonlightflower.wc3libs.misc.image.BLP.<init>(BLP.java:324)
	at net.moonlightflower.wc3libs.misc.image.Wc3RasterImg.ofInputStream(Wc3RasterImg.java:289)
	at ui.frames.InputMapPanel.displayMap(InputMapPanel.kt:130)
	at ui.frames.InputMapPanel.loadMap(InputMapPanel.kt:109)
	at worker.MapOpenWorker.doInBackground(MapOpenWorker.kt:23)
	at worker.MapOpenWorker.doInBackground(MapOpenWorker.kt:11)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

[war3mapMap.zip](https://github.com/inwc3/wc3libs/files/2719461/war3mapMap.zip)

**Comment by WaterKnight** [comment]
https://github.com/inwc3/wc3libs/commit/c24fc144d4bb53b134b8b0d4a05d085ba2a10e67

**Comment by Frotty** [comment]
Perfect 👍
