### ISSUE TITLE
StdGameExeFinder#get crashes on OS X

### ISSUE THREAD

**Issue by Frotty** [inwc3/wc3libs#44]
```
2019-08-08 00:04:22 [Wurst LanguageWorker] INFO  languageServer - received runMap command: map=/Users/roland/lots/Lots New Concept.w3x, wc3dir=/Users/roland/Downloads/Select your wc3 installation folder (optional), args=[-runcompiletimefunctions, -injectobjects, -stacktraces, -opt] 
2019-08-08 00:04:22 [Wurst LanguageWorker] WARN  languageServer - Exception occurred 
java.lang.UnsupportedOperationException: not a windows system: Mac OS X
	at net.moonlightflower.wc3libs.misc.WinRegistryHandler.<init>(WinRegistryHandler.java:15)
	at net.moonlightflower.wc3libs.port.RegistryGameExeFinder.getRegistryHandler(RegistryGameExeFinder.java:33)
	at net.moonlightflower.wc3libs.port.RegistryGameExeFinder.get(RegistryGameExeFinder.java:17)
	at net.moonlightflower.wc3libs.port.StdGameExeFinder.get(StdGameExeFinder.java:129)
	at de.peeeq.wurstio.utils.W3Utils.parsePatchVersion(W3Utils.java:53)
	at de.peeeq.wurstio.languageserver.requests.RunMap.execute(RunMap.java:77)
	at de.peeeq.wurstio.languageserver.requests.UserRequest.run(UserRequest.java:31)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$getNextWorkItem$1(LanguageWorker.java:171)
	at de.peeeq.wurstio.languageserver.LanguageWorker$Workitem.run(LanguageWorker.java:29)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:146)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by WaterKnight** [comment]
It's only a bug in the sense that the exception should already be thrown by StdGameExeFinder. I have no intel yet how to deal with Mac OS X.

**Comment by Frotty** [comment]
fixed?
