### ISSUE TITLE
cant read mdx

### ISSUE THREAD

**Issue by qq1053831109** [inwc3/wc3libs#52]
inclusiveSize [uint32]: 120 [78 00 00 00]
name [bytes]: [B@54c3b0dd [4E 61 6D 65 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00]
x [float32]: 0.0 [00 00 00 00]
y [float32]: 0.0 [00 00 00 00]
z [float32]: 0.0 [00 00 00 00]
fieldOfView [float32]: 0.0 [00 00 00 00]
farClippingPlane [float32]: 0.0 [00 00 00 00]
nearClippingPlane [float32]: 94.577 [6D 27 BD 42]
targetX [float32]: -37.0259 [86 1A 14 C2]
targetY [float32]: 148.277 [E9 46 14 43]
targetZ [float32]: 0.785398 [D8 0F 49 3F]
trackToken [id]:  @F [00 40 1C 46]
inclusiveSize [uint32]: 1176256512 [00 40 1C 46]
name [bytes]: null [00 00 80 3F DF E0 79 C1 6D 73 8E 40 7D 9F 00 43 ?]
	at net.moonlightflower.wc3libs.bin.BinInputStream.readBytes(BinInputStream.java:28)
	at net.moonlightflower.wc3libs.bin.Wc3BinInputStream.readBytes(Wc3BinInputStream.java:44)
	at net.moonlightflower.wc3libs.misc.model.mdx.Camera.<init>(Camera.java:468)
	at net.moonlightflower.wc3libs.misc.model.mdx.CameraChunk.read_0x0(CameraChunk.java:36)
	at net.moonlightflower.wc3libs.misc.model.mdx.CameraChunk.read(CameraChunk.java:55)
	at net.moonlightflower.wc3libs.misc.model.mdx.CameraChunk.<init>(CameraChunk.java:80)
	at net.moonlightflower.wc3libs.misc.model.MDX.lambda$read_0x0$42(MDX.java:223)
	at net.moonlightflower.wc3libs.misc.model.MDX.read_0x0(MDX.java:234)
	at net.moonlightflower.wc3libs.misc.model.MDX.read(MDX.java:265)
	at net.moonlightflower.wc3libs.misc.model.MDX.read_auto(MDX.java:254)
	at net.moonlightflower.wc3libs.misc.model.MDX.read(MDX.java:260)
	at net.moonlightflower.wc3libs.misc.model.MDX.read(MDX.java:292)
	at net.moonlightflower.wc3libs.misc.model.MDX.read(MDX.java:304)
	at net.moonlightflower.wc3libs.misc.model.MDX.<init>(MDX.java:319)
	at heduim.fastmap.test.TestMain.main(TestMain.java:29)

**Comment by WaterKnight** [comment]
The read values look like garbage. Can you give the model file?

**Comment by WaterKnight** [comment]
This looks like the same issue as https://github.com/inwc3/wc3libs/issues/76
It should be resolved with 64e514da962cfa9d353cb61abc670726608cb798. Closing here.
